### ISSUE TITLE
Problem with mne.channels.read_montage

### ISSUE THREAD

**Issue by YohanCaudron** [nice-tools/nice#10]
Dear all,

I'm a M2 student working on resting state EEG and I'm new to programming.
I'd like to use some of your nice tools but I get reccurent errors with the deprecated function read_channels from mne-python when trying to use or import functions : 
```
  File "C:\Users\yohan\Anaconda3\envs\hemispherotomy\lib\site-packages\nice\utils.py", line 30, in <module>
    from mne.channels import read_montage
ImportError: cannot import name 'read_montage' from 'mne.channels' (C:\Users\yohan\Anaconda3\envs\hemispherotomy\lib\site-packages\mne\channels\__init__.py)
```

Is there something I can do to fix this ? 

Thanks for you help,
Regards,

Yohan.

**Comment by fraimondo** [comment]
Hi Yohan,

Try installing NICE from the master branch. This has been corrected some time ago [here](https://github.com/nice-tools/nice/blob/ca1a59cf2d51c9664ec8231c355bfa51ffedea85/nice/utils.py#L30)
