### ISSUE TITLE
Can't import jivaro and ompk on windows platform

### ISSUE THREAD

**Issue by Mode5t** [nice-tools/nice#11]
I install nice and its Dependencies. When I run the /examples/compute_doc_forest_markers.py, and this happened
![image](https://user-images.githubusercontent.com/32796991/86740441-3c0ff800-c069-11ea-8d99-5dab4e11425e.png) 

I think Optimizations(optional) mean that it's not necessary to compile the c code. Did I get some misunderstand?
I don't know why these modules can't import, and I try to makefile on windows and Linux, but all fail. By the way, I know little about makefile, the tutorial only described the command on Unix, and the python path in the makefile is the format on Unix\Linux。
Help!

**Comment by fraimondo** [comment]
While it is not necessary to compile the C code, you have to parametrise the markers to not use them.

This is from the example you want to run:
https://github.com/nice-tools/nice/blob/ce9604b99afaa9af824e34e2e30755be74dc0720/examples/compute_doc_forest_markers.py#L94-L101

In your case, you might need to change the backend parameter to 'python' for these three markers.
