### ISSUE TITLE
import wsmi as jwsmi problem

### ISSUE THREAD

**Issue by OosterveldCas** [nice-tools/nice#15]
Dear people of nice-tools,
I have two questions regarding wSMI:

1. A problem in "test_connectivity.py" when trying to perform: "from nice.algorithms.optimizations.jivaro import wsmi as jwsmi", the file wsmi does not exist in jivaro.
It gives: ImportError: cannot import name 'wsmi' from 'nice.algorithms.optimizations.jivaro' (unknown location)

2. When I look at the file "connectivity.py", there appear to be two functions; "epochs_compute_wsmi" and "_wsmi_python", both described as compute wSMI. What is the difference exactly? 

I am rather new to these tools and Python in general, so help would be highly appreciated (: 

Thank you in advance!

**Comment by fraimondo** [comment]
> Dear people of nice-tools, I have two questions regarding wSMI:
> 
> 1. A problem in "test_connectivity.py" when trying to perform: "from nice.algorithms.optimizations.jivaro import wsmi as jwsmi", the file wsmi does not exist in jivaro.
>    It gives: ImportError: cannot import name 'wsmi' from 'nice.algorithms.optimizations.jivaro' (unknown location)

This is because you did not compile the C optimizations. Check here: https://nice-tools.github.io/nice/#optimizations-optional
Unfortunately we do not have many platforms to develop comprehensive instructions.


> 2. When I look at the file "connectivity.py", there appear to be two functions; "epochs_compute_wsmi" and "_wsmi_python", both described as compute wSMI. What is the difference exactly?
> 

Every function that starts with `_` is private. So you should not be calling those functions directly.


> I am rather new to these tools and Python in general, so help would be highly appreciated (:
> 
> Thank you in advance!

The easiest way is to use the `SymbolicMutualInformation` object:


```
from nice.markers import SymbolicMutualInformation
wsmi = SymbolicMutualInformation(
    tmin=None, tmax=None, method='weighted', backend='python',
    comment='weighted'),
wsmi.fit(epochs)
```

Then the computed wsmi data would be in  `wsmi.data_`

**Comment by OosterveldCas** [comment]
Thank you for the quick reply! So is "epochs" in wsmi.fit(epochs) the input data?

**Comment by fraimondo** [comment]
This are MNE epochs. The whole NICE package is meant to be used with MNE-Python.

**Comment by OosterveldCas** [comment]
Thank you, I have made some good progress. I do have some more questions: the returned data is 3d; 

For the purpose of my computation I want to have my wSMI output in excel, which requires a 2d format, how should I transform the data so that I simply have channels x epochs? 

Thank you in advance!

**Comment by fraimondo** [comment]
> On 13 Jun 2022, at 12:08, OosterveldCas ***@***.***> wrote:
>
> Thank you, I have made some good progress. I do have some more questions: the returned data is 3d; (channels, channels_y, epochs). Why are the channels presented twice? And what is the difference between channels and channels_y?

Yes, because wSMI is a measure of connectivity. So for each channel, you’ll get the connectivity values to the other channels.

> For the purpose of my computation I want to have my wSMI output in excel, which requires a 2d format, how should I transform the data so that I simply have channels x epochs?

You need to choose how you want to summarise the connectivity for each channel. In a few papers of ours, we use the median.
