### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Kiley1** [nice-tools/nice#19]
cannot import name 'pe' from 'nice.algorithms.optimizations.jivaro' (unknown location)这个怎么弄啊

**Comment by fraimondo** [comment]
why do you want to do that? This are part of the optimisations and need to be compiled. You can use the python version without compiling anything.

**Comment by Kiley1** [comment]
I am running the file Compute_ doc_ forest_ Markers.py, this is an example of a problem where no solution has been found. Can you help? Can you provide the data used in the paper? We are graduate students and need the data from your paper!!

**Comment by fraimondo** [comment]
You can change the `backend` parameter of Permutation Entropy and WSMI to `"python"` to avoid this error.

Regarding the data, unfortunately it can't be shared as it is medical data.

**Comment by Kiley1** [comment]
if backend == 'python':
        logger.info("Performing symbolic transformation")
        sym, count = _symb_python(fdata, kernel, tau)
        pe = np.nan_to_num(-np.nansum(count * np.log(count), axis=1))
    elif backend == 'c':
        from  nice.algorithms.optimizations.jivaro import pe as jpe
        pe, sym = jpe(fdata, kernel, tau)
    else:
        raise ValueError('backend %s not supported for PE'
                         % backend)
    nsym = math.factorial(kernel)
    pe = pe / np.log(nsym)
    return pe, sym
from  nice.algorithms.optimizations.jivaro import pe as jpe 
There is a problem here. There is no PE module in your file, resulting in an error report and no solution found. Therefore, I would like to consult you,",

**Comment by fraimondo** [comment]
The import is local and happens only if `backend == "c"`. If you don't know or can't compile the optimisations as in the README file, please use backend="python", and this error will not happen.

**Comment by Kiley1** [comment]
It is a pity that the default value of backend in the statement is python, but in
   if backend == 'python':
         logger.info("Performing symbolic transformation")
         sym, count = _symb_python(fdata, kernel, tau)
         pe = np.nan_to_num(-np.nansum(count * np.log(count), axis=1))
     elif backend == 'c':
         from nice.algorithms.optimizations.jivaro import pe as jpe
         pe, sym = jpe(fdata, kernel, tau)
     else:
         raise ValueError('backend %s not supported for PE'% backend)
He did not enter the if statement of backend=='python', but the elif backend=='c' statement, which is really annoying

**Comment by Kiley1** [comment]
![image](https://user-images.githubusercontent.com/127461512/227682807-7fbab6c6-1129-492d-b2fd-0555f33ed5b2.png)
很奇怪

**Comment by Kiley1** [comment]
Our research group is studying the code recently, and we need your data very much, and mentioned in your paper that if necessary, you can provide it. It is very necessary, thank you, it is the JSXXX-epo.fif, we downloaded the code and ran it It will show that the data inside is empty







                       
Original Email
                       
                     

Sender:"Fede Raimondo"< ***@***.*** &gt;;

Sent Time:2023/3/24 17:31

To:"nice-tools/nice"< ***@***.*** &gt;;

Cc recipient:"Kiley1"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [nice-tools/nice] question (Issue #19)




 
You can change the backend parameter of Permutation Entropy and WSMI to "python" to avoid this error.
 
Regarding the data, unfortunately it can't be shared as it is medical data.

**Comment by fraimondo** [comment]
If you are referring to [this paper](https://academic.oup.com/brain/article/141/11/3179/5114404) please contact the last author to present a formal data request.

**Comment by Kiley1** [comment]
Can you provide his email address, I can’t reach him through the current online information, our tutor is also urging us to complete the task as soon as possible, we need your data to complete the research, our very sincere request, just for research and learning ,Thank you so much

**Comment by fraimondo** [comment]
Yes you can reach him. Just google his name. I don't like posting email addresses on public websites that can be used by crawlers.

If your research depends on that data, then I would suggest that you change your research. That data is medical data, protected under several French and EU laws. The availability statement in the paper states that can be provided "upon reasonable request". This usually means that if there is a challenge to the results of the paper, and if there is enough evidence supporting this challenge, the original data could be asked to verify this challenge. However, this procedure involves gathering evidence (through data), as well as contacting the DPO, ethical commitee, etc. This will take a considerable amount of time and effort.

I just want to remind you that this is the code repository of an EEG analysis tool and not the proper channel to communicate to ask for data used in a paper. Please use the proper means of communication.
