### ISSUE TITLE
Problem with "epochs_compute_wsmi" function

### ISSUE THREAD

**Issue by Sirabhop** [nice-tools/nice#9]
I run this code to find brain connectivity

`wsmi, smi, sym, count = epochs_compute_wsmi(data, kernel = 32, tau = 41)`

(data is in the form of epoch.mne)
then the result shows

> ---> 56     system, n_channels = inst.info['description'].split('/')
>         57     dir_path = os.path.dirname(os.path.realpath(__file__))
>         58     if inst.info['description'].split('/')[0] == 'egi':
>         **AttributeError: 'NoneType' object has no attribute 'split'**

And, I've another question
If I want to compute wSMI of theta (4-8Hz) and alpha (8-12Hz), How should I compute it properly?

Thank you

**Comment by fraimondo** [comment]
Hi Sirabhop, that's a [pycsd](https://github.com/nice-tools/pycsd/) issue. I just fixed it.
